### ISSUE TITLE
makesd: outdated links

### ISSUE THREAD

**Issue by lukasc-ch** [Ascend/tools#1]
Two links of makesd are outdated or unreachable: 
1.  /makesd/for_20.1/make_sd_card.py on Line 45 refers to "https://raw.githubusercontent.com/Ascend/tools/master/versioninfo.yaml". This file does not exist and I could not find it anywhere. The use of "python make_sd_card.py internet" fails. This problem also applies when downloading the make_sd_card.py from ascend.huawei.com. Further, the script the recommends to look at a list of version (that it cannot load in the first place...) using "python3 sd_card_making.py list". The argument "list" is not supported by this script, though (cf. Lines 481ff.)
2. The link in the README.md in /makesd/for_20.1 point to http://cdimage.ubuntu.com/ubuntu/releases/18.04/release/ubuntu-18.04.4-server-arm64.iso. This is no longer reachable, and should point to: http://old-releases.ubuntu.com/releases/18.04.4/ubuntu-18.04.4-server-arm64.iso

**Comment by himanshu007-creator** [comment]
please assign me this issue
