### ISSUE TITLE
'make_sd_card.py' doesn't give an ERROR when file 'A200dk-npu-driver-*-ubuntu18.04-aarch64-minirc.tar.gz' is missing

### ISSUE THREAD

**Issue by NewComer00** [Ascend/tools#2]
### What happened
I was following the [document](https://www.hiascend.com/document/detail/zh/Atlas200DKDeveloperKit/1013/environment/atlased_04_0010.html) to make my SD card for 200DK.
I found if the file `A200dk-npu-driver-*-ubuntu18.04-aarch64-minirc.tar.gz` **doesn't exist**, the `ret` is still `True` and `driver_package_list` is `['']`.

https://github.com/Ascend/tools/blob/3cf484528e996b0f05c9341f1186bccc29e7bb56/makesd/generic_script/make_sd_card.py#L224-L232

So the python script **will not throw an ERROR** but continue running with `driver_pkg_file` equal to `""`, which will break the following lines:

https://github.com/Ascend/tools/blob/3cf484528e996b0f05c9341f1186bccc29e7bb56/makesd/generic_script/make_sd_card.py#L298-L300

`driver_package` is empty in the above command to be executed by shell. Finally the `make_ubuntu_sd.sh` will be executed with an input argument missing, and all the rest args will be messed up.

### The way to reproduce

Follow the [document](https://www.hiascend.com/document/detail/zh/Atlas200DKDeveloperKit/1013/environment/atlased_04_0010.html), but do not download the file `A200dk-npu-driver-*-ubuntu18.04-aarch64-minirc.tar.gz`.
The python script will give an error:

```
Begin to make SD Card...
disk /dev/sda size 31914983424, sector num 62333952
sector size 512
Please make sure you have installed dependency packages:
         apt-get install -y qemu-user-static binfmt-support gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
Please input Y: continue, other to install them:Y
Step: Start to make SD Card. It need some time, please wait...
Command:
bash /home/ant/mksd/make_ubuntu_sd.sh  /dev/sda /home/ant/mksd ubuntu-18.04.1-server-arm64.iso  none 192.168.0.2 192.168.1.2 62333952 512 >> /home/ant/mksd/sd_card_making_log/make_ubuntu_sd.log
[ERROR] Making SD Card failed, please check /home/ant/mksd/sd_card_making_log/make_ubuntu_sd.log for details!
ant@ant-TianYi510S-07ICK:~/mksd$ cat /home/ant/mksd/sd_card_making_log/make_ubuntu_sd.log
```

Then check the log file. It gives a very confusing and misleading error `Failed: Invalid usb card ip.`
That's because the args values for `make_ubuntu_sd.sh` have been messed up...

```
Begin to make SD Card...
disk /dev/sda size 31914983424, sector num 62333952
sector size 512
Step: Start to make SD Card. It need some time, please wait...
Command:
bash /home/ant/mksd/make_ubuntu_sd.sh  /dev/sda /home/ant/mksd ubuntu-18.04.1-server-arm64.iso  none 192.168.0.2 192.168.1.2 62333952 512 >> /home/ant/mksd/sd_card_making_log/make_ubuntu_sd.log
Partition naming without p-prefix
none
192.168.0.2
make_sd_process: 2%
Failed: Invalid usb card ip.
make sd car finished ,clean files
[ERROR] Making SD Card failed, please check /home/ant/mksd/sd_card_making_log/make_ubuntu_sd.log for details!
```

So I print the values of `ret` and `driver_package_list` in `make_sd_card.py` line 229:

```
Begin to make SD Card...
disk /dev/sda size 31914983424, sector num 62333952
sector size 512
Please make sure you have installed dependency packages:
         apt-get install -y qemu-user-static binfmt-support gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
Please input Y: continue, other to install them:Y
==========start==========
True
['']
==========end==========
Step: Start to make SD Card. It need some time, please wait...
Command:
bash /home/ant/mksd/make_ubuntu_sd.sh  /dev/sda /home/ant/mksd ubuntu-18.04.1-server-arm64.iso  none 192.168.0.2 192.168.1.2 62333952 512 >> /home/ant/mksd/sd_card_making_log/make_ubuntu_sd.log
[ERROR] Making SD Card failed, please check /home/ant/mksd/sd_card_making_log/make_ubuntu_sd.log for details!
```

I think the bug is here :smiley:

### My environment

Arch: x86_64
Platform: 20.04.1-Ubuntu
Kernel: 5.13.0-30-generic
Python: 3.8.10

**Comment by ascendhuawei** [comment]
Thanks for the great suggestion. We will look into it!
