### ISSUE TITLE
下载的rar文件损坏

### ISSUE THREAD

**Issue by Devincool** [Ascend/tools#35]
尝试了好几种方法，直接git clone报错，下载zip文件报错，还有没有别的下载链接，或者修复下？

**Comment by Technology-dog** [comment]
下载zip文件报错

**Comment by amanwalia92** [comment]
Goto the file you want to download, it will show you 
![view_raw](https://user-images.githubusercontent.com/8284681/65380438-217fb480-dccb-11e9-9ee6-6899cfd33f10.png)

Click on View Raw, the file will download.

**Comment by Devincool** [comment]
> Goto the file you want to download, it will show you
> ![view_raw](https://user-images.githubusercontent.com/8284681/65380438-217fb480-dccb-11e9-9ee6-6899cfd33f10.png)
> 
> Click on View Raw, the file will download.

Thanks very much!  It worked!
